Draft: Create lfai api zarf package
defenseunicorns/leapfrogai-api pull request #7
Opened 2023-10-23 23:32 UTC by YrrepNoj

2023-10-26 18:48 UTC, YrrepNoj commented on Makefile
> +VERSION ?= $(shell git describe --abbrev=0 --tags)
`?=` means 'set VERSION if it doesn't already exist. This allows us to default to using the git tags as the version but still have the freedom to specify something different if we want (`make docker-build VERSION=100.100.100`)

2023-10-26 18:51 UTC, YrrepNoj commented on .github/workflows/publish-zarf-package.yaml
> +      run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages
As an organization, we have been publishing all zarf packages under the `/packages` namespace on GHCR. I would like to try to keep that pattern for the leapfrog team.

https://github.com/orgs/defenseunicorns/packages?tab=packages&q=packages%2F

2023-10-26 18:53 UTC, YrrepNoj commented on .github/workflows/publish-zarf-package.yaml
> +      run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages
What does the team think about publishing LFAI packages `/packages/leapfrogai/` ???

2023-10-26 18:54 UTC, YrrepNoj commented on Makefile
> +docker-build:
good call, I'll update the push to go to `defenseunicorns/leapfrogai`

2023-10-26 18:57 UTC, YrrepNoj commented on chart/values.yaml
> +  enabled: false
Hmm, I'll make this into a zarf variable for now so it can be dynamically set a deploy time.

2023-10-30 14:39 UTC, gerred commented on .github/workflows/publish-zarf-package.yaml
> +      run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages
I'm good with this pattern, let's follow convention!

2023-10-30 14:42 UTC, gerred commented on Makefile
> +docker-build:
(based on other convo, this would actually then be `defenseunicorns/packages/leapfrogai` then if we all agree on that convention, yeah?)

2023-10-30 14:43 UTC, justinthelaw commented on .github/workflows/publish-zarf-package.yaml
> +      run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages
We should have a quick huddle tomorrow to talk through this after/at standup? Just want to make sure I understand the standardization and what things we need to transition over to this pattern that haven't been following it. @gerred @gphorvath @YrrepNoj @CollectiveUnicorn

2023-10-31 16:18 UTC, YrrepNoj commented on Makefile
> +docker-build:
@gerred Soooo not for the docker image. Maybe? 

docker images: `defenseunicorns/leapfrogai`
zarf packages: `defenseunicorns/packages/leapfrogai`

2023-10-31 17:33 UTC, gerred requested changes

2023-10-31 17:33 UTC, gerred commented on chart/Chart.yaml
> +      image: ghcr.io/defenseunicorns/leapfrogai-api:0.1.0"
is there a typo here? see an end quote but no beginning quote

2023-10-31 17:33 UTC, gerred commented on utils/config.py
> +import toml
not for this PR for changes, but we should really look at something like confz + pydantic in a future PR. considering using it in the leapfrogai pypi config.

2023-10-31 18:13 UTC, YrrepNoj commented on chart/Chart.yaml
> +      image: ghcr.io/defenseunicorns/leapfrogai-api:0.1.0"
removed for now

2023-10-31 20:45 UTC, gerred approved these changes

2023-10-31 20:46 UTC, merged